---
title: "Reports"
---

This page provides links to download PDF reports describing the findings and methodologies used to to identify the geographic and demographic characteristics of communities across New England that are:

1. overburdened by current transportation-related emissions and related externalities; 
2. at increased risk for heat island effects, which is exacerbated by climate change and transportation related air pollution;
3. likely to experience evacuation risks and other transportation-related vulnerabilities resulting from flooding, extreme weather, and other climate stressors, and
4. underserved by current public transit infrastructure or services and overburdened by transportation related costs. 

[Executive Summary of Investing for Equity: Using an Environmental Justice Approach to Guide Transportation and Climate Investments Interactive Tool (29MB)](reports/Transportation Equitable Investment Report EXEC.pdf)

[Full Report (all states) of Investing for Equity: Using an Environmental Justice Approach to Guide Transportation and Climate Investments Interactive Tool (29MB)](reports/Transportation Equitable Investment Report FINAL.pdf)

---

## State-level fact sheets

* [CONNECTICUT](reports/Fact_Sheet_CT.pdf)
* [MASSACHUSETTS](reports/Fact_Sheet_MA.pdf)
* [NEW HAMPSHIRE](reports/Fact_Sheet_NH.pdf)
* [MAINE](reports/Fact_Sheet_ME.pdf)
* [RHODE ISLAND](reports/Fact_Sheet_RI.pdf)
* [VERMONT](reports/Fact_Sheet_VT.pdf)

---

## State-level full reports

* [CONNECTICUT](reports/Investing_For_Equity_CT.pdf)
* [MASSACHUSETTS](reports/Investing_For_Equity_MA.pdf)
* [NEW HAMPSHIRE](reports/Investing_For_Equity_NH.pdf)
* [MAINE](reports/Investing_For_Equity_ME.pdf)
* [RHODE ISLAND](reports/Investing_For_Equity_RI.pdf)
* [VERMONT](reports/Investing_For_Equity_VT.pdf)

---

## State-level technical reports (analytic methodology and data sources)

### Connecticut

* [Emissions](reports/Emissions_ConnecticutPDF.pdf)
* [Transportation](reports/Transport_ConnecticutPDF.pdf)
* [Heat](reports/LST_ConnecticutPDF.pdf)
* [Evacuation](reports/Evacuation_ConnecticutPDF.pdf)

### Massachusetts

* [Emissions](reports/Emissions_MassachusettsPDF.pdf)
* [Transportation](reports/Transport_MassachusettsPDF.pdf)
* [Heat](reports/LST_MassachusettsPDF.pdf)
* [Evacuation](reports/Evacuation_MassachusettsPDF.pdf)

### Maine

* [Emissions](reports/Emissions_MainePDF.pdf)
* [Transportation](reports/Transport_MainePDF.pdf)
* [Heat](reports/LST_MainePDF.pdf)
* [Evacuation](reports/Evacuation_MainePDF.pdf)

### NewHampshire

* [Emissions](reports/Emissions_NewHampshirePDF.pdf)
* [Transportation](reports/Transport_NewHampshirePDF.pdf)
* [Heat](reports/LST_NewHampshirePDF.pdf)
* [Evacuation](reports/Evacuation_NewHampshirePDF.pdf)

### RhodeIsland

* [Emissions](reports/Emissions_RhodeIslandPDF.pdf)
* [Transportation](reports/Transport_RhodeIslandPDF.pdf)
* [Heat](reports/LST_RhodeIslandPDF.pdf)
* [Evacuation](reports/Evacuation_RhodeIslandPDF.pdf)

### Vermont

* [Emissions](reports/Emissions_VermontPDF.pdf)
* [Transportation](reports/Transport_VermontPDF.pdf)
* [Heat](reports/LST_VermontPDF.pdf)
* [Evacuation](reports/Evacuation_VermontPDF.pdf)